<programa> ::= <declaracoes>

<declaracoes> ::= <declaracao> | <declaracao> <declaracoes>

<declaracao> ::= <declaracao_variavel>
               | <declaracao_funcao>
               | <declaracao_controle>
               | <declaracao_estrutura>
               | <declaracao_excecao>

<declaracao_variavel> ::= <tipo> <defina> <identificador> [ "=" <expressao> ] ";"

<declaracao_funcao> ::= <faca> <identificador> "(" [ <parametros> ] ")" <corpo_funcao> <retorne> [ <expressao> ] ";"

<corpo_funcao> ::= <declaracoes>

<declaracao_controle> ::= <decida> "(" <expressao> ")" <corpo_controle> <caso_contrario> <corpo_controle>

<corpo_controle> ::= <declaracoes>

<declaracao_estrutura> ::= <tipo_estrutura> <identificador> "[" <expressao> "]" ";"

<tipo> ::= "numero" | "texto" | "sinal" | "byte" | "vazio" | "conjunto" | "mapa_chave"

<tipo_estrutura> ::= "estrutura"

<parametros> ::= <identificador> [ "," <parametros> ]

<retorne> ::= "retorne"

<expressao> ::= <termo> | <expressao> <operador_aritmetico> <termo>

<termo> ::= <fator> | <termo> <operador_aritmetico> <fator>

<fator> ::= <numero> | <texto> | <identificador> | "(" <expressao> ")"

<operador_aritmetico> ::= "+" | "-" | "*" | "/"

<identificador> ::= <letra> <identificador_opcional>

<identificador_opcional> ::= <letra> <identificador_opcional> | <digito> <identificador_opcional> | ""

<numero> ::= <digito> | <digito> <numero>

<digito> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

<letra> ::= "a" | "b" | "c" | ... | "z" | "A" | "B" | ... | "Z"

<comando> ::= <movimento> | <acao> | <interacao>

<movimento> ::= "andar" <direcao>

<direcao> ::= "esquerda" | "direita" | "frente" | "atras" | "agachar" | "pular"

<acao> ::= "atacar" <alvo> | "defender" | "fugir" | "esconder" | "usar_poder"

<alvo> ::= <inimigo> | <objeto>

<inimigo> ::= "inimigo" | "monstro" | "criatura"

<objeto> ::= "tesouro" | "item" | "arma" | "pocao" | "chave"

<interacao> ::= "pegar" <objeto> | "usar" <objeto> | "examinar" <objeto> | "falar" <inimigo> | "abrir" <objeto> | "soltar" <objeto>
